// File generated by FlutterFire CLI - Manually recreated
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZBzUpPtWHnW3mlF38L7YGpiknMB9dZb8',
    appId: '1:782891273844:web:750619b1bfe1939e52cb21', // Using fake web ID based on android format
    messagingSenderId: '782891273844',
    projectId: 'halisepetimbl',
    authDomain: 'halisepetimbl.firebaseapp.com',
    storageBucket: 'halisepetimbl.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZBzUpPtWHnW3mlF38L7YGpiknMB9dZb8',
    appId: '1:782891273844:android:750619b1bfe1939e52cb21',
    messagingSenderId: '782891273844',
    projectId: 'halisepetimbl',
    storageBucket: 'halisepetimbl.firebasestorage.app',
  );
}
